version: "3.8"

services:
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - "5436:5432"
    volumes:
      - .database:/var/lib/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
  app:
    container_name: app
    build: ./
    ports:
      - "8081:8081"
      - "8082:8082"
    depends_on:
      db:
        condition: service_healthy
