POST http://localhost:8081/createShortLink
Content-Type: application/json

{"link": "https://gist.github.com/4"}

###

GET http://localhost:8081/getInitialLink/4FhXDb57pV

###

GET http://localhost:8081/fED3uhrko4

