POST http://localhost:8081/createShortLink
Content-Type: application/json

{"link": "https://gist.github.com/"}

###

GET http://localhost:8081/getInitialLink/tV8iFQHRwm

###

GET http://localhost:8081/tV8iFQHRwm
